name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: ./firsttry-site
      - name: Build
        run: npm run build --if-present
        working-directory: ./firsttry-site
      - name: Lint (if configured)
        run: npm run lint --if-present || true
        working-directory: ./firsttry-site
